UserStoryBoard/UserStoryBoard/Models/Backlog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserStoryBoard.Models
{
    public class Backlog : InfoTemplate
    {
        public static int Columns { get; set; } = 4;
        public static string[] ColumnNames { get; set; } = new string[] { "Lav ", "Mellem", "Høj", "Haster" };
        public List<UserStory> UserStoriesInBacklog { get; set; } = new List<UserStory>();

        private static int nextId = 0;

        public Backlog()
        {
        }

        public Backlog(string name, string descr) : base(name)
        {
            Id = nextId++;
            //Columns = cols;
            Description = descr;

            CreationDate = DateTime.Now;
        }
    }
}

UserStoryBoard/UserStoryBoard/Pages/Backlogs/BacklogUserStory.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryBoard.Interface;
using UserStoryBoard.Models;

namespace UserStoryBoard.Pages
{
    public class BacklogUserStoryModel : PageModel
    {
        //private BoardService boardService;
        IBoards boards;
        //public Board CurrentBoard { get; set; }

        private int boardId;

        public BacklogUserStoryModel(IBoards repo)
        {
            boards = repo;
            //boardService = bService;
        }
        public IActionResult OnGet(int id)
        {
            boardId = id;

            return Page();
        }

        // For refreshing the page when moving a card
        public IActionResult OnGetColumn(int boardId, int userStoryId, int column, bool backlog)
        {
            UserStory updated = boards.GetUserStory(userStoryId, boardId, backlog);

            int result = updated.ColumnId + column;
            if (result > -1 && result < Board.Columns)
            {
                updated.ColumnId = result; // FUCK THIS
                if (backlog) updated.Priority = result; // IF WE ARE IN THE BACKLOG, REMEMBER TO UPDATE THE PRIORITY AS WELL, AS THAT'S WHAT THE COLUMNS REPRESENT.

                boards.UpdateUserStory(updated, boards.GetBoard(boardId).Id, backlog);
            }

            return Page();
        }

        public IActionResult OnGetMovedUserStoryFromBoard(int boardId, int userStoryId)
        {
            UserStory updated = boards.GetUserStory(userStoryId, boardId, false);

            updated.ColumnId = 0; // FUCK THIS
            boards.MoveToBacklog(updated, boards.GetBoard(boardId).Id);

            return Page();
        }

        public Board GetCurrentBoard()
        {
            return boards.GetBoard(boardId);
        }
        public List<UserStory> GetUserStories()
        {
            return boards.GetUserStoriesInBacklog(boardId);
        }
    }
}

UserStoryBoard/UserStoryBoard/Pages/Boards/KanbanBoard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using UserStoryBoard.Interface;
using UserStoryBoard.Models;

namespace UserStoryBoard.Pages
{
    public class KanbanBoardModel : PageModel
    {
        //private BoardService boardService;
        IBoards boards;

        [BindProperty]
        public UserStory UserStory { get; set; }


        private int boardId;

        public KanbanBoardModel(IBoards repo)
        {
            boards = repo;
            //boardService = bService;
        }
        public IActionResult OnGet(int id)
        {
            boardId = id;

            return Page();
        }

        // For refreshing the page when moving a card
        public IActionResult OnGetColumn(int boardId, int userStoryId, int column, bool backlog)
        {
            UserStory updated = boards.GetUserStory(userStoryId, boardId, backlog);

            int result = updated.ColumnId + column;
            if (result > -1 && result < Board.Columns)
            {
                updated.ColumnId = result; // FUCK THIS
                if (backlog) updated.Priority = result; // IF WE ARE IN THE BACKLOG, REMEMBER TO UPDATE THE PRIORITY AS WELL, AS THAT'S WHAT THE COLUMNS REPRESENT.

                boards.UpdateUserStory(updated, boards.GetBoard(boardId).Id, backlog);
            }

            return Page();
        }

        public IActionResult OnGetMovedUserStoryFromBacklog(int boardId, int userStoryId)
        {
            UserStory updated = boards.GetUserStory(userStoryId, boardId, true);

            updated.ColumnId = 0; // FUCK THIS
            boards.MoveToBoard(updated, boards.GetBoard(boardId).Id);

            return Page();
        }

        public Board GetCurrentBoard()
        {
            return boards.GetBoard(boardId);
        }
        public List<UserStory> GetUserStories()
        {
            return boards.GetUserStories(boardId);
        }
    }
}

UserStoryBoard/UserStoryBoard/Pages/Backlogs/BacklogUserStory.cshtml
@page "{id:int}/{backlog:bool}"
@using global::UserStoryBoard.Models
@model UserStoryBoard.Pages.BacklogUserStoryModel
@{
    <h1>Backlog for @Model.GetCurrentBoard().Name</h1>
    <div class="container-fluid p-md-4" style="background-color:#181A1E;">
        <div class="mb-2">
            <a class="btn btn-success" type="button" asp-page="../UserStories/CreateUserStory" asp-route-id="@Model.GetCurrentBoard().Id" asp-route-backlog=@true>
                <i class="fa fa-plus"></i>
            </a>
            <a class="btn btn-info" type="button" asp-page="../Boards/KanbanBoard" asp-route-id="@Model.GetCurrentBoard().Id" asp-route-backlog=@false>
                <i class="fa fa-folder-open"></i>
            </a>
        </div>
        <div class="row align-items-start">
            @for (int i = 0; i < Backlog.Columns; i++)
            {
                <div class="col-3" onmouseup="card_drop(card_drag_id, this, @Model.GetCurrentBoard().Id, @i)" style="min-height: 200px">
                    <h2>@Backlog.ColumnNames[i]</h2>
                    @foreach (UserStory userStory in Model.GetUserStories())
                    {
                        @if (userStory.ColumnId == i)
                        {
                            <div class="card mb-2" style="width: 95%" id="@userStory.Id">
                                <div class="card-header p-2" onmousedown="card_drag(@userStory.Id)">
                                    <h5 class="card-title text-white">
                                        <small class="text-muted">(@userStory.Id)</small> @userStory.Name
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">Board ID: @userStory.BoardId</p>
                                    <p class="card-text text-white">@userStory.Description</p>
                                </div>
                                <div class="card-footer m-sm-1">
                                    <a class="btn btn-secondary m-sm-1" type="button" asp-page="../UserStories/UserStoryDetail" asp-route-id="@userStory.Id" asp-route-boardId="@userStory.BoardId" asp-route-backlog="@true">
                                        <i class="fa fa-info-circle"></i>
                                    </a>
                                    <a class="btn btn-warning m-sm-1" type="button" asp-page="../UserStories/EditUserStory" asp-route-id="@userStory.Id" asp-route-boardId="@userStory.BoardId" asp-route-backlog="@true">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger m-sm-1" type="button" asp-page="../UserStories/DeleteUserStory" asp-route-id="@userStory.Id" asp-route-boardId="@userStory.BoardId" asp-route-backlog="@true">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                    <a class="btn btn-dark m-sm-1" type="button" asp-page="BacklogUserStory" asp-route-boardId="@userStory.BoardId" asp-route-userStoryId="@userStory.Id" asp-route-column="@(-1)" asp-page-handler="Column">
                                        <i class="fa fa-arrow-left"></i>
                                    </a>
                                    <a class="btn btn-dark m-sm-1" type="button" asp-page="BacklogUserStory" asp-route-boardId="@userStory.BoardId" asp-route-userStoryId="@userStory.Id" asp-route-column="@(1)" asp-page-handler="Column">
                                        <i class="fa fa-arrow-right"></i>
                                    </a>
                                    <a class="btn btn-info m-sm-1" type="button" asp-page="../Boards/KanbanBoard" asp-route-id="@userStory.Id" asp-route-boardId="@userStory.BoardId" asp-route-backlog="@false" asp-page-handler="MovedUserStoryFromBacklog">
                                        <i class="fa fa-step-forward"></i>
                                    </a>
                                </div>
                            </div>
                        }
                    }
                </div>
            }
        </div>
    </div>
}